me5413_world:
  # the frame of all the poses below
  frame_id: 'world'

  # robot starting point
  start:
    x: 0.0
    y: 0.0
    yaw: 0.0

  # assembly line poses
  assembly_line_1:
    x: 4.0
    y: -1.7
    yaw: -1.57
  assembly_line_2:
    x: 4.0
    y: -4.7
    yaw: -1.57

  # packing area poses
  # packing_area_1:
  #   x: 13.0
  #   y: -0.6
  #   yaw: -1.57
  # packing_area_2:
  #   x: 10.0
  #   y: -0.6
  #   yaw: -1.57
  # packing_area_3:
  #   x: 10.0
  #   y: -3.5
  #   yaw: -1.57
  # packing_area_4:
  #   x: 13.0
  #   y: -3.5
  #   yaw: -1.57

  # delivery vehicle poses
  vehicle_1:
    x: 15.5
    y: -8.2
    yaw: -1.57
  vehicle_2:
    x: 2.9
    y: -9.9
    yaw: 0.0
  vehicle_3:
    x: 2.9
    y: -13.1
    yaw: 0.0
    
# 导航参数
navigation:
  goal_positions:
    - {name: "exploration_point", x: 1.0, y: 10.0, theta: 0.0}
    - {name: "box_area", x: 5.0, y: 8.0, theta: 1.57}
    - {name: "finish_point", x: 0.0, y: 0.0, theta: 0.0}
  
# 检测参数
detection:
  timeout: 10.0  # 检测超时时间
  topic: "/box_detector/position"